import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import useCheckWidth from "@/components/Helpers";

export const metadata: Metadata = {
  title: "Shivank Tyagi",
  description: "Generated by Shivank Tyagi",
  icons: {
    icon: "/images/st.png", // Correct path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const width = useCheckWidth;
  console.log(width, "width")
  return (
    <html lang="en">
      <body className="container ">
        <div className="d-flex justify-content-center gap-6 my-16" style={{
          height: "auto",

        }}>
          <Sidebar />
          <div
            className="w-75 position-relative  "
            style={{
              maxWidth: "100%",
              border: '1px solid #383838',
              borderRadius: "20px",
              backgroundColor: "#1e1e1f",
              height: "auto",
            }}
          >
            <Navbar />
            <main >{children}</main>
          </div>

        </div>
      </body>
    </html>
  );
}
