import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";



export const metadata: Metadata = {
  title: "Shivank Tyagi",
  description: "Generated by Shivank Tyagi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container-sm  p-8">
        <Sidebar />
        {/* <main>{children}</main> */}
      </body>
    </html>
  );
}
